-- dup_detect schema export
-- Tables: 4

USE ${DB_NAME_DUP_DETECT};

-- Table: WORKFLOW_MASTER (1 rows)
DROP TABLE IF EXISTS `WORKFLOW_MASTER`;
CREATE TABLE `WORKFLOW_MASTER` (
  `Id` int NOT NULL,
  `Collection_Code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FDE_JSON` json DEFAULT NULL,
  `DUP_JSON` json DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: WORK_ITEM_BIN (28 rows)
DROP TABLE IF EXISTS `WORK_ITEM_BIN`;
CREATE TABLE `WORK_ITEM_BIN` (
  `WORK_ITEM_BIN_ID` bigint NOT NULL AUTO_INCREMENT,
  `ICL_FILE_ID` bigint DEFAULT NULL,
  `CASH_LETTER_ID` bigint DEFAULT NULL,
  `BUSINESS_DATE` date DEFAULT NULL,
  `BIN_NUMBER` varchar(20) DEFAULT NULL,
  `COLLECTION_TYPE` char(10) DEFAULT NULL,
  `COLLECTION_CODE` varchar(20) DEFAULT NULL,
  `SYS_ENTERED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `SYS_EXPIRY_DATE` timestamp NULL DEFAULT NULL,
  `SYS_TOTAL_ITEMS` bigint DEFAULT NULL,
  `SYS_DEBIT_AMOUNT` varchar(50) DEFAULT NULL,
  `SYS_CREDIT_AMOUNT` varchar(10) DEFAULT NULL,
  `TOTAL_DUP_COUNT` varchar(15) DEFAULT NULL,
  `SYS_REMAINING_REVIEW` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`WORK_ITEM_BIN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=56 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: WORK_ITEM_CHECK_DETAILS (73 rows)
DROP TABLE IF EXISTS `WORK_ITEM_CHECK_DETAILS`;
CREATE TABLE `WORK_ITEM_CHECK_DETAILS` (
  `WICD_ID` bigint NOT NULL AUTO_INCREMENT,
  `WORK_ITEM_BIN_ID` bigint DEFAULT NULL,
  `ACCOUNT` char(20) DEFAULT NULL,
  `ROUTING_TRANSIT` char(20) DEFAULT NULL,
  `AMOUNT` char(14) DEFAULT NULL,
  `PROCESS_CONTROL` char(32) DEFAULT NULL,
  `AUX_ON_US` varchar(64) DEFAULT NULL,
  `EXT_PROC_CODE` char(32) DEFAULT NULL,
  `SENDER_RT` bigint DEFAULT NULL,
  `SENDER_ISN` bigint DEFAULT NULL,
  `RECORD_ID` bigint DEFAULT NULL,
  `IMAGE_S3_LOCATION` varchar(200) DEFAULT NULL,
  `BUSINESS_DATE` timestamp NULL DEFAULT NULL,
  `BATCH_TRACK_NUM` char(18) DEFAULT NULL,
  `ONUS_FLAG` char(1) DEFAULT NULL,
  `PAYMENT_ID` bigint DEFAULT NULL,
  `SYS_DUP` char(1) DEFAULT '0',
  `SYS_ENTERED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `SYS_EXPIRY_DATE` timestamp NULL DEFAULT NULL,
  `SYS_DELETED` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`WICD_ID`),
  KEY `FK_WICD_BIN` (`WORK_ITEM_BIN_ID`),
  CONSTRAINT `FK_WICD_BIN` FOREIGN KEY (`WORK_ITEM_BIN_ID`) REFERENCES `WORK_ITEM_BIN` (`WORK_ITEM_BIN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=228 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: WORK_ITEM_CHECK_DUPLICATE (132 rows)
DROP TABLE IF EXISTS `WORK_ITEM_CHECK_DUPLICATE`;
CREATE TABLE `WORK_ITEM_CHECK_DUPLICATE` (
  `ORIG_WICD_ID` bigint NOT NULL,
  `DUP_WICD_ID` bigint NOT NULL,
  `ORIG_BUSINESS_DAY` date DEFAULT NULL,
  `DUP_BUSINESS_DAY` date DEFAULT NULL,
  `ORIG_IMAGE_S3_LOC` varchar(200) DEFAULT NULL,
  `DUP_IMAGE_S3_LOC` varchar(200) DEFAULT NULL,
  `SYS_ENTERED_DATE` date DEFAULT NULL,
  `SYS_EXPIRY_DATE` date DEFAULT NULL,
  `SYS_REVIEW_USER` varchar(50) DEFAULT NULL,
  `SYS_REVIEW_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ORIG_WICD_ID`,`DUP_WICD_ID`),
  KEY `FK_DUP_DUP` (`DUP_WICD_ID`),
  CONSTRAINT `FK_DUP_DUP` FOREIGN KEY (`DUP_WICD_ID`) REFERENCES `WORK_ITEM_CHECK_DETAILS` (`WICD_ID`),
  CONSTRAINT `FK_DUP_ORIG` FOREIGN KEY (`ORIG_WICD_ID`) REFERENCES `WORK_ITEM_CHECK_DETAILS` (`WICD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

