-- check_payment_platform schema export
-- Tables: 39

USE ${DB_NAME_PRIMARY};

-- Table: ACCOUNT_PRODUCT_LIMIT (14 rows)
DROP TABLE IF EXISTS `ACCOUNT_PRODUCT_LIMIT`;
CREATE TABLE `ACCOUNT_PRODUCT_LIMIT` (
  `PRODUCT_CODE` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PRODUCT_NAME` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PRODUCT_FAMILY` enum('CONSUMER','SMB','COMMERCIAL','SPECIAL') COLLATE utf8mb4_unicode_ci NOT NULL,
  `MAX_CHECK_AMOUNT` decimal(18,2) NOT NULL,
  `CURRENCY_CODE` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'USD',
  `MAX_DAILY_TOTAL` decimal(18,2) DEFAULT NULL,
  `MAX_MONTHLY_TOTAL` decimal(18,2) DEFAULT NULL,
  `REQUIRES_POSPAY` tinyint NOT NULL DEFAULT '0',
  `POSPAY_THRESHOLD` decimal(18,2) DEFAULT NULL,
  `EFFECTIVE_DATE` date NOT NULL,
  `EXPIRY_DATE` date DEFAULT NULL,
  `ACTIVE_FLAG` tinyint NOT NULL DEFAULT '1',
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`PRODUCT_CODE`),
  KEY `IDX_FAMILY_ACTIVE` (`PRODUCT_FAMILY`,`ACTIVE_FLAG`),
  KEY `IDX_EFFECTIVE` (`EFFECTIVE_DATE`,`EXPIRY_DATE`,`ACTIVE_FLAG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: ADE_ADJUSTMENT_HISTORY (3 rows)
DROP TABLE IF EXISTS `ADE_ADJUSTMENT_HISTORY`;
CREATE TABLE `ADE_ADJUSTMENT_HISTORY` (
  `ADJUSTMENT_HISTORY_ID` int NOT NULL AUTO_INCREMENT,
  `ADJUSTMENT_ID` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PAYMENT_ID` bigint NOT NULL,
  `ADJUSTMENT_TYPE` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ORIGINAL_AMOUNT` decimal(15,2) NOT NULL,
  `CORRECTED_AMOUNT` decimal(15,2) NOT NULL,
  `DELTA_AMOUNT` decimal(15,2) NOT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ADJUSTMENT_HISTORY_ID`),
  KEY `idx_aah_adjustment_id` (`ADJUSTMENT_ID`),
  KEY `idx_aah_payment_id` (`PAYMENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: ADE_APPROVAL_RULES (6 rows)
DROP TABLE IF EXISTS `ADE_APPROVAL_RULES`;
CREATE TABLE `ADE_APPROVAL_RULES` (
  `RULE_ID` int NOT NULL AUTO_INCREMENT,
  `COLLECTION_CODE` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CORRECTION_TYPE` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `THRESHOLD_AMOUNT` decimal(15,2) NOT NULL DEFAULT '0.00',
  `REQUIRES_APPROVAL` tinyint(1) NOT NULL DEFAULT '0',
  `ALLOWED_ROLES` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`RULE_ID`),
  UNIQUE KEY `idx_aar_collection_type` (`COLLECTION_CODE`,`CORRECTION_TYPE`),
  KEY `idx_aar_active` (`ACTIVE`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: ADE_CORRECTION_LOG (6 rows)
DROP TABLE IF EXISTS `ADE_CORRECTION_LOG`;
CREATE TABLE `ADE_CORRECTION_LOG` (
  `ADJUSTMENT_ID` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PAYMENT_ID` bigint NOT NULL,
  `CORRECTION_CLASSIFICATION` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CORRECTED_FIELDS_JSON` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ORIGINAL_FIELDS_JSON` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `OPERATOR_ID` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `OPERATOR_ROLE` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `REASON_CODE` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `NOTES` text COLLATE utf8mb4_unicode_ci,
  `APPROVAL_STATUS` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NOT_REQUIRED',
  `ROUTING_DECISION` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ADJUSTMENT_ID`),
  KEY `idx_acl_payment_id` (`PAYMENT_ID`),
  KEY `idx_acl_created_at` (`CREATED_AT`),
  KEY `idx_acl_operator_id` (`OPERATOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: BANK (0 rows)
DROP TABLE IF EXISTS `BANK`;
CREATE TABLE `BANK` (
  `BANK_IDENTIFIER` int NOT NULL,
  `BANK_NAME` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ROUTING_NUMBER` char(9) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RETURN_ROUTING_NUMBER` char(9) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CONTACT_FIRST_NAME` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CONTACT_LAST_NAME` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CONTACT_MIDDLE_NAME` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CONTACT_PHONE_NUMBER` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STREET_ADDRESS` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS_LINE_2` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CITY_NAME` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STATE_CODE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `COUNTRY_NAME` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREATION_DATE` timestamp NULL DEFAULT NULL,
  `CREATED_BY` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`BANK_IDENTIFIER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: BUNDLE_DETAILS (152 rows)
DROP TABLE IF EXISTS `BUNDLE_DETAILS`;
CREATE TABLE `BUNDLE_DETAILS` (
  `BUNDLE_ID` bigint NOT NULL AUTO_INCREMENT,
  `FILE_ID` bigint DEFAULT NULL,
  `CASHLTR_ID` bigint DEFAULT NULL,
  `BUNDLE_INDEX` int DEFAULT NULL,
  `COLLECTION_TYPE` smallint DEFAULT NULL,
  `ECE_RT` char(9) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BUSINESS_DATE` char(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BUNDLE_CREATION_DATE` char(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_BUNDLE_ID` char(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_CYCLE_NUM` char(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BATCH_NUMBER` int DEFAULT NULL,
  PRIMARY KEY (`BUNDLE_ID`),
  KEY `FILE_ID` (`FILE_ID`),
  KEY `CASHLTR_ID` (`CASHLTR_ID`),
  CONSTRAINT `BUNDLE_DETAILS_ibfk_1` FOREIGN KEY (`FILE_ID`) REFERENCES `INBOUND_FILE_DETAILS` (`FILE_ID`),
  CONSTRAINT `BUNDLE_DETAILS_ibfk_2` FOREIGN KEY (`CASHLTR_ID`) REFERENCES `CASH_LETTER_DETAILS` (`CASHLTR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=166 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: BUNDLE_DETAILS_REC (286 rows)
DROP TABLE IF EXISTS `BUNDLE_DETAILS_REC`;
CREATE TABLE `BUNDLE_DETAILS_REC` (
  `FILE_ID` bigint NOT NULL,
  `CASHLTR_ID` bigint NOT NULL,
  `BUNDLE_ID` bigint NOT NULL,
  `RECORD_TYPE` smallint NOT NULL,
  `RECORD_DATA` mediumtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`FILE_ID`,`CASHLTR_ID`,`BUNDLE_ID`,`RECORD_TYPE`),
  KEY `BUNDLE_ID` (`BUNDLE_ID`),
  CONSTRAINT `BUNDLE_DETAILS_REC_ibfk_1` FOREIGN KEY (`BUNDLE_ID`) REFERENCES `BUNDLE_DETAILS` (`BUNDLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: BUSINESS_DAY (26 rows)
DROP TABLE IF EXISTS `BUSINESS_DAY`;
CREATE TABLE `BUSINESS_DAY` (
  `BDAY_ID` bigint NOT NULL,
  `BUSINESS_DATE` timestamp NULL DEFAULT NULL,
  `CATEGORY` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STATE` char(9) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREDIT_AMOUNT` decimal(15,2) DEFAULT NULL,
  `CREDIT_COUNT` int DEFAULT NULL,
  `DEBIT_AMOUNT` decimal(15,2) DEFAULT NULL,
  `DEBIT_COUNT` int DEFAULT NULL,
  PRIMARY KEY (`BDAY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: CASH_LETTER_DETAILS (154 rows)
DROP TABLE IF EXISTS `CASH_LETTER_DETAILS`;
CREATE TABLE `CASH_LETTER_DETAILS` (
  `CASHLTR_ID` bigint NOT NULL AUTO_INCREMENT,
  `FILE_ID` bigint DEFAULT NULL,
  `CASH_LETTER_INDEX` int DEFAULT NULL,
  `CASH_LETTER_ID` char(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BUSINESS_DATE` char(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREATION_DATE` char(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREATION_TIME` char(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REC_TYPE` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DOC_TYPE` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `WORK_TYPE` char(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NUM_BUNDLES` int DEFAULT NULL,
  `BIN_NUMBER` int DEFAULT NULL,
  `COLLECTION_TYPE` smallint DEFAULT NULL,
  `COLLECTION_CODE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PROCESSING_BUS_DATE` date DEFAULT NULL,
  `BALANCED_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `BIN_CREATED_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `IQV_TIFF_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `IQV_IQA_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `IQV_IUA_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `IQV_FRAUD_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `IQV_OPR_REVIEWED_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `CDE_REPAIR_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `DUP_DETECTED_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `DUP_REVIEWED_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `IMAGE_ARCHIVED_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `POSTING_EXTRACTED_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `ADJUSTED_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  PRIMARY KEY (`CASHLTR_ID`),
  KEY `FILE_ID` (`FILE_ID`),
  CONSTRAINT `CASH_LETTER_DETAILS_ibfk_1` FOREIGN KEY (`FILE_ID`) REFERENCES `INBOUND_FILE_DETAILS` (`FILE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=174 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: CASH_LETTER_DETAILS_REC (286 rows)
DROP TABLE IF EXISTS `CASH_LETTER_DETAILS_REC`;
CREATE TABLE `CASH_LETTER_DETAILS_REC` (
  `FILE_ID` bigint NOT NULL,
  `CASHLTR_ID` bigint NOT NULL,
  `RECORD_TYPE` smallint NOT NULL,
  `RECORD_DATA` mediumtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`FILE_ID`,`CASHLTR_ID`,`RECORD_TYPE`),
  KEY `CASHLTR_ID` (`CASHLTR_ID`),
  CONSTRAINT `CASH_LETTER_DETAILS_REC_ibfk_1` FOREIGN KEY (`CASHLTR_ID`) REFERENCES `CASH_LETTER_DETAILS` (`CASHLTR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: CL_BUILD_REQUEST (6 rows)
DROP TABLE IF EXISTS `CL_BUILD_REQUEST`;
CREATE TABLE `CL_BUILD_REQUEST` (
  `BUILD_REQUEST_ID` varchar(64) NOT NULL,
  `BUSINESS_DATE` date NOT NULL,
  `WORK_TYPE` varchar(20) DEFAULT NULL,
  `SOURCE_SYSTEM` varchar(50) DEFAULT NULL,
  `REQUEST_TYPE` varchar(30) DEFAULT NULL,
  `COLLECTION_CODE` varchar(20) DEFAULT NULL,
  `CLOSE_POLICY_JSON` json DEFAULT NULL,
  `PRIORITY` varchar(10) DEFAULT 'NORMAL',
  `REQUESTED_BY` varchar(100) DEFAULT NULL,
  `CORRELATION_ID` varchar(100) DEFAULT NULL,
  `STATUS` varchar(30) NOT NULL DEFAULT 'RECEIVED',
  `ITEM_COUNT` int DEFAULT '0',
  `FAILED_ITEM_COUNT` int DEFAULT '0',
  `ERROR_DETAILS` text,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`BUILD_REQUEST_ID`),
  KEY `idx_cbr_status` (`STATUS`),
  KEY `idx_cbr_bdate` (`BUSINESS_DATE`),
  KEY `idx_cbr_correlation` (`CORRELATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: CL_BUILD_REQUEST_BIN (7 rows)
DROP TABLE IF EXISTS `CL_BUILD_REQUEST_BIN`;
CREATE TABLE `CL_BUILD_REQUEST_BIN` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `BUILD_REQUEST_ID` varchar(64) NOT NULL,
  `BIN_NUMBER` int NOT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `idx_cbrb_bin` (`BIN_NUMBER`),
  KEY `idx_cbrb_br` (`BUILD_REQUEST_ID`),
  CONSTRAINT `CL_BUILD_REQUEST_BIN_ibfk_1` FOREIGN KEY (`BUILD_REQUEST_ID`) REFERENCES `CL_BUILD_REQUEST` (`BUILD_REQUEST_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: CL_BUNDLE (3 rows)
DROP TABLE IF EXISTS `CL_BUNDLE`;
CREATE TABLE `CL_BUNDLE` (
  `BUNDLE_ID` bigint NOT NULL AUTO_INCREMENT,
  `CASH_LETTER_ID` bigint NOT NULL,
  `BUNDLE_INDEX` int NOT NULL DEFAULT '1',
  `DEST_RT` varchar(9) DEFAULT NULL,
  `ORIG_RT` varchar(9) DEFAULT NULL,
  `ITEM_COUNT` int DEFAULT '0',
  `TOTAL_AMOUNT` decimal(15,2) DEFAULT '0.00',
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`BUNDLE_ID`),
  KEY `idx_cb_cl` (`CASH_LETTER_ID`),
  CONSTRAINT `CL_BUNDLE_ibfk_1` FOREIGN KEY (`CASH_LETTER_ID`) REFERENCES `CL_CASH_LETTER` (`CASH_LETTER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: CL_CASH_LETTER (3 rows)
DROP TABLE IF EXISTS `CL_CASH_LETTER`;
CREATE TABLE `CL_CASH_LETTER` (
  `CASH_LETTER_ID` bigint NOT NULL AUTO_INCREMENT,
  `FILE_SESSION_ID` bigint NOT NULL,
  `CASH_LETTER_INDEX` int NOT NULL DEFAULT '1',
  `DEST_RT` varchar(9) DEFAULT NULL,
  `ORIG_RT` varchar(9) DEFAULT NULL,
  `COLLECTION_TYPE` varchar(5) DEFAULT NULL,
  `RECORD_TYPE` varchar(5) DEFAULT NULL,
  `DOC_TYPE` varchar(5) DEFAULT NULL,
  `WORK_TYPE` varchar(10) DEFAULT NULL,
  `ITEM_COUNT` int DEFAULT '0',
  `TOTAL_AMOUNT` decimal(15,2) DEFAULT '0.00',
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CASH_LETTER_ID`),
  KEY `idx_ccl_session` (`FILE_SESSION_ID`),
  CONSTRAINT `CL_CASH_LETTER_ibfk_1` FOREIGN KEY (`FILE_SESSION_ID`) REFERENCES `CL_FILE_SESSION` (`FILE_SESSION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: CL_FILE_PROFILE (2 rows)
DROP TABLE IF EXISTS `CL_FILE_PROFILE`;
CREATE TABLE `CL_FILE_PROFILE` (
  `FILE_PROFILE_ID` bigint NOT NULL AUTO_INCREMENT,
  `PROFILE_NAME` varchar(50) NOT NULL,
  `FORMAT_TYPE` varchar(30) NOT NULL COMMENT 'X9_FORWARD_STD or X9_RETURN_ICLR',
  `DEST_RT` varchar(9) NOT NULL,
  `ORIG_RT` varchar(9) NOT NULL,
  `DEST_NAME` varchar(50) DEFAULT NULL,
  `ORIG_NAME` varchar(50) DEFAULT NULL,
  `STANDARD_LEVEL` varchar(5) DEFAULT '35',
  `TEST_INDICATOR` varchar(1) DEFAULT 'T',
  `COUNTRY_CODE` varchar(5) DEFAULT 'US',
  `MAX_BUNDLE_ITEMS` int DEFAULT '300',
  `ACTIVE` tinyint(1) NOT NULL DEFAULT '1',
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`FILE_PROFILE_ID`),
  UNIQUE KEY `idx_cfp_name` (`PROFILE_NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: CL_FILE_SESSION (3 rows)
DROP TABLE IF EXISTS `CL_FILE_SESSION`;
CREATE TABLE `CL_FILE_SESSION` (
  `FILE_SESSION_ID` bigint NOT NULL AUTO_INCREMENT,
  `SESSION_KEY_HASH` varchar(64) NOT NULL,
  `BUSINESS_DATE` date NOT NULL,
  `FLOW_TYPE` varchar(10) NOT NULL COMMENT 'FORWARD or RETURN',
  `ENDPOINT_RT` varchar(9) NOT NULL,
  `FILE_PROFILE_ID` bigint NOT NULL,
  `STATUS` varchar(20) NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN, CLOSED, GENERATING, GENERATED, ERROR',
  `ITEM_COUNT` int NOT NULL DEFAULT '0',
  `TOTAL_AMOUNT` decimal(15,2) NOT NULL DEFAULT '0.00',
  `VERSION` int NOT NULL DEFAULT '1',
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CLOSED_AT` timestamp NULL DEFAULT NULL,
  `LAST_APPEND_AT` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`FILE_SESSION_ID`),
  UNIQUE KEY `idx_cfs_hash` (`SESSION_KEY_HASH`),
  KEY `idx_cfs_status` (`STATUS`),
  KEY `idx_cfs_bdate` (`BUSINESS_DATE`),
  KEY `FILE_PROFILE_ID` (`FILE_PROFILE_ID`),
  CONSTRAINT `CL_FILE_SESSION_ibfk_1` FOREIGN KEY (`FILE_PROFILE_ID`) REFERENCES `CL_FILE_PROFILE` (`FILE_PROFILE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: CL_ITEM_ASSIGNMENT (3 rows)
DROP TABLE IF EXISTS `CL_ITEM_ASSIGNMENT`;
CREATE TABLE `CL_ITEM_ASSIGNMENT` (
  `ASSIGNMENT_ID` bigint NOT NULL AUTO_INCREMENT,
  `PAYMENT_ID` bigint NOT NULL,
  `BUILD_REQUEST_ID` varchar(64) NOT NULL,
  `FILE_SESSION_ID` bigint NOT NULL,
  `CASH_LETTER_ID` bigint DEFAULT NULL,
  `BUNDLE_ID` bigint DEFAULT NULL,
  `FLOW_TYPE` varchar(10) NOT NULL,
  `ENDPOINT_RT` varchar(9) NOT NULL,
  `STATUS` varchar(20) NOT NULL DEFAULT 'ASSIGNED' COMMENT 'ASSIGNED, IN_CLOSED_FILE, APPROVED, TRANSMITTED, REJECTED, ERROR',
  `ERROR_DETAILS` text,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ASSIGNMENT_ID`),
  KEY `CASH_LETTER_ID` (`CASH_LETTER_ID`),
  KEY `BUNDLE_ID` (`BUNDLE_ID`),
  KEY `idx_cia_payment` (`PAYMENT_ID`),
  KEY `idx_cia_session` (`FILE_SESSION_ID`),
  KEY `idx_cia_br` (`BUILD_REQUEST_ID`),
  KEY `idx_cia_status` (`STATUS`),
  CONSTRAINT `CL_ITEM_ASSIGNMENT_ibfk_1` FOREIGN KEY (`BUILD_REQUEST_ID`) REFERENCES `CL_BUILD_REQUEST` (`BUILD_REQUEST_ID`),
  CONSTRAINT `CL_ITEM_ASSIGNMENT_ibfk_2` FOREIGN KEY (`FILE_SESSION_ID`) REFERENCES `CL_FILE_SESSION` (`FILE_SESSION_ID`),
  CONSTRAINT `CL_ITEM_ASSIGNMENT_ibfk_3` FOREIGN KEY (`CASH_LETTER_ID`) REFERENCES `CL_CASH_LETTER` (`CASH_LETTER_ID`),
  CONSTRAINT `CL_ITEM_ASSIGNMENT_ibfk_4` FOREIGN KEY (`BUNDLE_ID`) REFERENCES `CL_BUNDLE` (`BUNDLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: CL_X9_FILE (3 rows)
DROP TABLE IF EXISTS `CL_X9_FILE`;
CREATE TABLE `CL_X9_FILE` (
  `X9_FILE_ID` bigint NOT NULL AUTO_INCREMENT,
  `FILE_SESSION_ID` bigint NOT NULL,
  `FILE_PROFILE_ID` bigint NOT NULL,
  `FILE_NAME` varchar(255) DEFAULT NULL,
  `FILE_SIZE_BYTES` bigint DEFAULT NULL,
  `CHECKSUM_SHA256` varchar(64) DEFAULT NULL,
  `ITEM_COUNT` int DEFAULT '0',
  `TOTAL_AMOUNT` decimal(15,2) DEFAULT '0.00',
  `STATUS` varchar(30) NOT NULL DEFAULT 'PENDING_REVIEW' COMMENT 'PENDING_REVIEW, APPROVED, REJECTED, TRANSMITTED, GENERATION_ERROR',
  `S3_URI` varchar(500) DEFAULT NULL,
  `VALIDATION_STATUS` varchar(20) DEFAULT NULL,
  `VALIDATION_DETAILS` text,
  `APPROVED_BY` varchar(100) DEFAULT NULL,
  `REJECTED_BY` varchar(100) DEFAULT NULL,
  `TRANSMITTED_AT` timestamp NULL DEFAULT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`X9_FILE_ID`),
  KEY `FILE_PROFILE_ID` (`FILE_PROFILE_ID`),
  KEY `idx_cx9_status` (`STATUS`),
  KEY `idx_cx9_session` (`FILE_SESSION_ID`),
  CONSTRAINT `CL_X9_FILE_ibfk_1` FOREIGN KEY (`FILE_SESSION_ID`) REFERENCES `CL_FILE_SESSION` (`FILE_SESSION_ID`),
  CONSTRAINT `CL_X9_FILE_ibfk_2` FOREIGN KEY (`FILE_PROFILE_ID`) REFERENCES `CL_FILE_PROFILE` (`FILE_PROFILE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: ENGINE_ERROR_LOG (82 rows)
DROP TABLE IF EXISTS `ENGINE_ERROR_LOG`;
CREATE TABLE `ENGINE_ERROR_LOG` (
  `ERROR_ID` bigint NOT NULL AUTO_INCREMENT,
  `ENGINE_NAME` varchar(30) NOT NULL,
  `SEVERITY` varchar(10) NOT NULL DEFAULT 'ERROR',
  `FILE_ID` bigint DEFAULT NULL,
  `CASHLETTER_ID` bigint DEFAULT NULL,
  `PAYMENT_ID` bigint DEFAULT NULL,
  `ERROR_CODE` varchar(50) DEFAULT NULL,
  `ERROR_MESSAGE` varchar(500) NOT NULL,
  `STACK_TRACE` text,
  `SQS_MESSAGE_BODY` text,
  `CONTEXT_DATA` text,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ERROR_ID`),
  KEY `IDX_ENGINE` (`ENGINE_NAME`),
  KEY `IDX_SEVERITY` (`SEVERITY`),
  KEY `IDX_FILE` (`FILE_ID`),
  KEY `IDX_CASHLETTER` (`CASHLETTER_ID`),
  KEY `IDX_PAYMENT` (`PAYMENT_ID`),
  KEY `IDX_CREATED` (`CREATED_AT`)
) ENGINE=InnoDB AUTO_INCREMENT=83 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: EXCEPTION_MASTER (27 rows)
DROP TABLE IF EXISTS `EXCEPTION_MASTER`;
CREATE TABLE `EXCEPTION_MASTER` (
  `exception_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception_category` enum('FRAUD','POSTING','IMAGE') COLLATE utf8mb4_unicode_ci NOT NULL,
  `priority_band` enum('P0','P1','P2','P3','P4') COLLATE utf8mb4_unicode_ci NOT NULL,
  `rank_in_band` int NOT NULL,
  `ops_repairable_flag` tinyint(1) NOT NULL DEFAULT '0',
  `default_queue` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `default_x9_code` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `active_flag` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`exception_code`),
  UNIQUE KEY `uk_exception_rank` (`priority_band`,`rank_in_band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: EXCEPTION_WORKFLOW_RULE (23 rows)
DROP TABLE IF EXISTS `EXCEPTION_WORKFLOW_RULE`;
CREATE TABLE `EXCEPTION_WORKFLOW_RULE` (
  `exception_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue_name` enum('FRAUD_REVIEW','POSTING_REVIEW','IMAGE_REVIEW','AMOUNT_REVIEW','MICR_REVIEW','DATE_REVIEW','ENDORSEMENT_REVIEW','SIGNATURE_REVIEW') COLLATE utf8mb4_unicode_ci NOT NULL,
  `ops_can_key_amount` tinyint(1) NOT NULL DEFAULT '0',
  `ops_can_key_date` tinyint(1) NOT NULL DEFAULT '0',
  `ops_can_key_payee` tinyint(1) NOT NULL DEFAULT '0',
  `ops_can_key_micr_rt` tinyint(1) NOT NULL DEFAULT '0',
  `ops_can_key_micr_acct` tinyint(1) NOT NULL DEFAULT '0',
  `ops_can_key_micr_serial` tinyint(1) NOT NULL DEFAULT '0',
  `if_success_next_state` enum('CONTINUE','REEVALUATE') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CONTINUE',
  `if_fail_action` enum('RETURN') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'RETURN',
  `if_fail_x9_code` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `active_flag` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`exception_code`),
  CONSTRAINT `fk_workflow_exception` FOREIGN KEY (`exception_code`) REFERENCES `EXCEPTION_MASTER` (`exception_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: EXCEPTION_X9_CONDITION_MAP (20 rows)
DROP TABLE IF EXISTS `EXCEPTION_X9_CONDITION_MAP`;
CREATE TABLE `EXCEPTION_X9_CONDITION_MAP` (
  `exception_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `condition_type` enum('NONE','POSPAY_STOP_VOID','REVIEW_OUTCOME') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NONE',
  `condition_value` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `x9_return_code` char(1) COLLATE utf8mb4_unicode_ci NOT NULL,
  `active_flag` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`exception_code`,`condition_type`,`condition_value`),
  CONSTRAINT `fk_x9map_exception` FOREIGN KEY (`exception_code`) REFERENCES `EXCEPTION_MASTER` (`exception_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: HOST_BANK (0 rows)
DROP TABLE IF EXISTS `HOST_BANK`;
CREATE TABLE `HOST_BANK` (
  `BANK_IDENTIFIER` int NOT NULL,
  `BANK_NAME` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ROUTING_NUMBER` char(9) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RETURN_ROUTING_NUMBER` char(9) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CONTACT_FIRST_NAME` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CONTACT_LAST_NAME` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CONTACT_MIDDLE_NAME` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CONTACT_PHONE_NUMBER` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STREET_ADDRESS` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS_LINE_2` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CITY_NAME` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STATE_CODE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `COUNTRY_NAME` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREATION_DATE` timestamp NULL DEFAULT NULL,
  `CREATED_BY` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`BANK_IDENTIFIER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: IA_ARCHIVE_FILE (3 rows)
DROP TABLE IF EXISTS `IA_ARCHIVE_FILE`;
CREATE TABLE `IA_ARCHIVE_FILE` (
  `FILE_ID` bigint NOT NULL AUTO_INCREMENT,
  `REQUEST_ID` bigint NOT NULL,
  `BIN_NUMBER` int NOT NULL,
  `BUSINESS_DATE` date NOT NULL,
  `FILE_FORMAT` varchar(10) NOT NULL COMMENT 'CIFF or COF',
  `FILE_NAME` varchar(255) NOT NULL,
  `FILE_PATH` varchar(500) DEFAULT NULL,
  `FILE_SIZE_BYTES` bigint DEFAULT NULL,
  `ITEM_COUNT` int DEFAULT '0',
  `CHECKSUM` varchar(64) DEFAULT NULL COMMENT 'SHA-256 hex digest',
  `S3_KEY` varchar(500) DEFAULT NULL,
  `S3_UPLOAD_TS` timestamp NULL DEFAULT NULL,
  `STATUS` varchar(30) NOT NULL DEFAULT 'GENERATED',
  `ERROR_DETAILS` text,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`FILE_ID`),
  KEY `idx_iaf_status` (`STATUS`),
  KEY `idx_iaf_bin` (`BIN_NUMBER`),
  KEY `idx_iaf_bdate` (`BUSINESS_DATE`),
  KEY `idx_iaf_req` (`REQUEST_ID`),
  KEY `idx_iaf_format` (`FILE_FORMAT`),
  CONSTRAINT `IA_ARCHIVE_FILE_ibfk_1` FOREIGN KEY (`REQUEST_ID`) REFERENCES `IA_ARCHIVE_REQUEST` (`REQUEST_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: IA_ARCHIVE_ITEM (3 rows)
DROP TABLE IF EXISTS `IA_ARCHIVE_ITEM`;
CREATE TABLE `IA_ARCHIVE_ITEM` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `FILE_ID` bigint NOT NULL,
  `PAYMENT_ID` bigint NOT NULL,
  `BIN_NUMBER` int NOT NULL,
  `INCLUSION_STATUS` varchar(20) NOT NULL DEFAULT 'INCLUDED' COMMENT 'INCLUDED, MISSING_FRONT_IMAGE, MISSING_BACK_IMAGE, FAILED',
  `FRONT_IMAGE_SIZE` bigint DEFAULT '0',
  `BACK_IMAGE_SIZE` bigint DEFAULT '0',
  `ERROR_DETAILS` text,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `idx_iai_file` (`FILE_ID`),
  KEY `idx_iai_payment` (`PAYMENT_ID`),
  KEY `idx_iai_bin` (`BIN_NUMBER`),
  KEY `idx_iai_status` (`INCLUSION_STATUS`),
  CONSTRAINT `IA_ARCHIVE_ITEM_ibfk_1` FOREIGN KEY (`FILE_ID`) REFERENCES `IA_ARCHIVE_FILE` (`FILE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: IA_ARCHIVE_REQUEST (2 rows)
DROP TABLE IF EXISTS `IA_ARCHIVE_REQUEST`;
CREATE TABLE `IA_ARCHIVE_REQUEST` (
  `REQUEST_ID` bigint NOT NULL AUTO_INCREMENT,
  `ARCHIVE_REQUEST_ID` varchar(64) NOT NULL,
  `BUSINESS_DATE` date NOT NULL,
  `COLLECTION_CODE` varchar(20) DEFAULT NULL,
  `WORK_TYPE` varchar(20) DEFAULT NULL,
  `SOURCE_SYSTEM` varchar(50) DEFAULT NULL,
  `PRIORITY` varchar(10) DEFAULT 'NORMAL',
  `REQUESTED_BY` varchar(100) DEFAULT NULL,
  `CORRELATION_ID` varchar(100) DEFAULT NULL,
  `STATUS` varchar(30) NOT NULL DEFAULT 'RECEIVED',
  `TOTAL_FILES` int DEFAULT '0',
  `TOTAL_ITEMS` int DEFAULT '0',
  `FAILED_ITEMS` int DEFAULT '0',
  `PROCESSING_DURATION_MS` bigint DEFAULT NULL,
  `ERROR_DETAILS` text,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`REQUEST_ID`),
  UNIQUE KEY `ARCHIVE_REQUEST_ID` (`ARCHIVE_REQUEST_ID`),
  KEY `idx_iar_status` (`STATUS`),
  KEY `idx_iar_bdate` (`BUSINESS_DATE`),
  KEY `idx_iar_collection` (`COLLECTION_CODE`),
  KEY `idx_iar_correlation` (`CORRELATION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: IA_ARCHIVE_REQUEST_BIN (2 rows)
DROP TABLE IF EXISTS `IA_ARCHIVE_REQUEST_BIN`;
CREATE TABLE `IA_ARCHIVE_REQUEST_BIN` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `REQUEST_ID` bigint NOT NULL,
  `BIN_NUMBER` int NOT NULL,
  `ITEM_COUNT` int DEFAULT '0',
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `idx_iarb_bin` (`BIN_NUMBER`),
  KEY `idx_iarb_req` (`REQUEST_ID`),
  CONSTRAINT `IA_ARCHIVE_REQUEST_BIN_ibfk_1` FOREIGN KEY (`REQUEST_ID`) REFERENCES `IA_ARCHIVE_REQUEST` (`REQUEST_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: IMAGE_DATA (296 rows)
DROP TABLE IF EXISTS `IMAGE_DATA`;
CREATE TABLE `IMAGE_DATA` (
  `PAYMENT_ID` bigint NOT NULL,
  `BDAY_ID` bigint DEFAULT NULL,
  `IMAGE_SEQ_NUM` bigint NOT NULL,
  `FBW_IMAGE` mediumblob,
  `RBW_IMAGE` mediumblob,
  `FGS_IMAGE` mediumblob,
  `RGS_IMAGE` mediumblob,
  PRIMARY KEY (`PAYMENT_ID`,`IMAGE_SEQ_NUM`),
  KEY `BDAY_ID` (`BDAY_ID`),
  CONSTRAINT `IMAGE_DATA_ibfk_1` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `ITEM_DETAILS` (`PAYMENT_ID`),
  CONSTRAINT `IMAGE_DATA_ibfk_2` FOREIGN KEY (`BDAY_ID`) REFERENCES `BUSINESS_DAY` (`BDAY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: INBOUND_FILE_DETAILS (180 rows)
DROP TABLE IF EXISTS `INBOUND_FILE_DETAILS`;
CREATE TABLE `INBOUND_FILE_DETAILS` (
  `FILE_ID` bigint NOT NULL AUTO_INCREMENT,
  `DEST_RT` char(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_RT` char(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREATION_DATE` char(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREATION_TIME` char(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FILE_ID_MOD` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DEBIT_ITEM_COUNT` int DEFAULT NULL,
  `DEBIT_ITEM_AMOUNT` decimal(16,2) DEFAULT NULL,
  `CREDIT_ITEM_COUNT` int DEFAULT NULL,
  `CREDIT_ITEM_AMOUNT` decimal(16,2) DEFAULT NULL,
  `TOTAL_RECORDS` int DEFAULT NULL,
  `CUST_FILENAME` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RCVD_FILENAME` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DESTINATION_NAME` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIGINATION_NAME` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TEST_INDICATOR` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TRANSMISSION_SIZE` bigint DEFAULT NULL,
  `FILE_INGESTION_STATUS` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FILE_FDV_STATUS` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ERROR_MESSAGE` text COLLATE utf8mb4_unicode_ci,
  `FILE_INGESTION_DATE` datetime DEFAULT NULL,
  `FILE_INGESTION_ERROR_MESSAGE` text COLLATE utf8mb4_unicode_ci,
  `FILE_FDV_ERROR_MESSAGE` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`FILE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=205 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: INBOUND_FILE_DETAILS_REC (286 rows)
DROP TABLE IF EXISTS `INBOUND_FILE_DETAILS_REC`;
CREATE TABLE `INBOUND_FILE_DETAILS_REC` (
  `FILE_ID` bigint NOT NULL,
  `RECORD_TYPE` smallint NOT NULL,
  `RECORD_DATA` mediumtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`FILE_ID`,`RECORD_TYPE`),
  CONSTRAINT `INBOUND_FILE_DETAILS_REC_ibfk_1` FOREIGN KEY (`FILE_ID`) REFERENCES `INBOUND_FILE_DETAILS` (`FILE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: ITEM_AUDIT_TRAIL (888 rows)
DROP TABLE IF EXISTS `ITEM_AUDIT_TRAIL`;
CREATE TABLE `ITEM_AUDIT_TRAIL` (
  `AUDIT_ID` bigint NOT NULL AUTO_INCREMENT,
  `PAYMENT_ID` int NOT NULL,
  `FILE_ID` int DEFAULT NULL,
  `CASHLETTER_ID` int DEFAULT NULL,
  `BDAY_ID` int DEFAULT NULL,
  `COLLECTION_CODE` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EVENT_TYPE` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `EVENT_STATUS` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `SCORE` decimal(10,4) DEFAULT NULL,
  `ERROR_CODES` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EVENT_DETAILS` text COLLATE utf8mb4_unicode_ci,
  `PERFORMED_BY` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `EVENT_TIMESTAMP` datetime(3) NOT NULL,
  `CREATED_AT` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`AUDIT_ID`),
  KEY `idx_payment_id` (`PAYMENT_ID`),
  KEY `idx_event_type` (`EVENT_TYPE`),
  KEY `idx_cashletter_id` (`CASHLETTER_ID`),
  KEY `idx_bday_id` (`BDAY_ID`),
  KEY `idx_event_timestamp` (`EVENT_TIMESTAMP`)
) ENGINE=InnoDB AUTO_INCREMENT=1006 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: ITEM_DETAILS (296 rows)
DROP TABLE IF EXISTS `ITEM_DETAILS`;
CREATE TABLE `ITEM_DETAILS` (
  `PAYMENT_ID` bigint NOT NULL AUTO_INCREMENT,
  `BDAY_ID` bigint DEFAULT NULL,
  `FILE_ID` bigint NOT NULL,
  `CASHLETTER_ID` bigint NOT NULL,
  `BUNDLE_ID` bigint NOT NULL,
  `FIELD_1` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIELD_2` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIELD_3` varchar(35) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIELD_4` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIELD_5` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIELD_6` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIELD_7` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIELD_8` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_MICR_AMOUNT` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_MICR_ONUS` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_MICR_EPC` varchar(9) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_MICR_RT` varchar(9) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_MICR_AUXONUS` varchar(17) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OCR_MICR_AMOUNT` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OCR_MICR_PC` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OCR_MICR_ACCOUNT` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OCR_MICR_FIELD4` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OCR_MICR_RT` varchar(9) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OCR_MICR_EPC` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OCR_MICR_AUXONUS` varchar(17) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AMOUNT` decimal(15,2) DEFAULT NULL,
  `BOFD_BUSINESS_DATE` date DEFAULT NULL,
  `BOFD_SEQ_NUM` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BOFD_ORIG_RT` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_MICR_ACCOUNT` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_MICR_SERIAL` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`PAYMENT_ID`),
  KEY `BDAY_ID` (`BDAY_ID`),
  KEY `FILE_ID` (`FILE_ID`),
  KEY `CASHLETTER_ID` (`CASHLETTER_ID`),
  KEY `BUNDLE_ID` (`BUNDLE_ID`),
  CONSTRAINT `ITEM_DETAILS_ibfk_1` FOREIGN KEY (`BDAY_ID`) REFERENCES `BUSINESS_DAY` (`BDAY_ID`),
  CONSTRAINT `ITEM_DETAILS_ibfk_2` FOREIGN KEY (`FILE_ID`) REFERENCES `INBOUND_FILE_DETAILS` (`FILE_ID`),
  CONSTRAINT `ITEM_DETAILS_ibfk_3` FOREIGN KEY (`CASHLETTER_ID`) REFERENCES `CASH_LETTER_DETAILS` (`CASHLTR_ID`),
  CONSTRAINT `ITEM_DETAILS_ibfk_4` FOREIGN KEY (`BUNDLE_ID`) REFERENCES `BUNDLE_DETAILS` (`BUNDLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=308 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: ITEM_DETAILS_ENRICHED (271 rows)
DROP TABLE IF EXISTS `ITEM_DETAILS_ENRICHED`;
CREATE TABLE `ITEM_DETAILS_ENRICHED` (
  `PAYMENT_ID` bigint NOT NULL DEFAULT '0',
  `BDAY_ID` bigint DEFAULT NULL,
  `FILE_ID` bigint NOT NULL,
  `CASHLETTER_ID` bigint NOT NULL,
  `BUNDLE_ID` bigint NOT NULL,
  `FIELD_1` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIELD_2` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIELD_3` varchar(35) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIELD_4` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIELD_5` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIELD_6` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIELD_7` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIELD_8` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_MICR_AMOUNT` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_MICR_ONUS` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_MICR_EPC` varchar(9) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_MICR_RT` varchar(9) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_MICR_AUXONUS` varchar(17) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OCR_MICR_AMOUNT` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OCR_MICR_PC` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OCR_MICR_ACCOUNT` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OCR_MICR_FIELD4` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OCR_MICR_RT` varchar(9) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OCR_MICR_EPC` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OCR_MICR_AUXONUS` varchar(17) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AMOUNT` decimal(15,2) DEFAULT NULL,
  `BOFD_BUSINESS_DATE` date DEFAULT NULL,
  `BOFD_SEQ_NUM` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BOFD_ORIG_RT` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIG_MICR_ACCOUNT` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_01` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_02` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_03` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_04` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_05` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_06` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_07` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_08` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_09` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_10` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_11` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_12` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_13` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_14` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_15` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_16` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_17` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_18` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_19` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_20` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_21` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_22` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_23` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_24` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHED_DATA_25` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHMENT_STATUS` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHMENT_EXCEPTION_CODE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHMENT_EXCEPTION_DETAILS` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENRICHMENT_ERROR_CODE` int DEFAULT NULL,
  `IQV_STATUS` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IQV_ERROR_CODES` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DQV_STATUS` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DQV_ERROR_CODES` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BR_ENGINE_STATUS` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DUP_DETECT_STATUS` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ROUTING_DESTINATION` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ROUTING_REASON` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PROCESSING_STATUS` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PROCESSING_STARTED_AT` datetime DEFAULT NULL,
  `PROCESSING_COMPLETED_AT` datetime DEFAULT NULL,
  `ADJUSTMENT_ID` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FORWARD_ENDPOINT` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RETURN_ENDPOINT` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OPS_SCREEN_ORIGIN` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OPS_DECISION` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OPS_OPERATOR_ID` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OPS_NOTES` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OPS_DECISION_TIMESTAMP` datetime DEFAULT NULL,
  `DISPOSITION_STATUS` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CL_BUILD_STATUS` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Build request ID that reserved this item',
  `CL_FILE_SESSION_ID` bigint DEFAULT NULL COMMENT 'FK to cl_file_session',
  `CL_FILE_ID` bigint DEFAULT NULL COMMENT 'FK to cl_x9_file',
  `CL_BUNDLE_ID` bigint DEFAULT NULL COMMENT 'FK to cl_bundle',
  `CL_ITEM_STATUS` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ELIGIBLE, RESERVED, ASSIGNED_TO_OPEN_FILE, etc.',
  `CL_TRANSMITTED_TS` timestamp NULL DEFAULT NULL COMMENT 'Timestamp when item was transmitted to S3',
  `IA_ARCHIVE_STATUS` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ARCHIVED, ARCHIVE_FAILED, or NULL',
  `IA_ARCHIVE_FILE_ID` bigint DEFAULT NULL COMMENT 'FK to IA_ARCHIVE_FILE.FILE_ID',
  `IA_ARCHIVED_TS` timestamp NULL DEFAULT NULL COMMENT 'Timestamp when item was archived',
  `ORIG_MICR_SERIAL` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  KEY `idx_ide_adjustment_id` (`ADJUSTMENT_ID`),
  KEY `idx_ide_cl_status` (`CL_ITEM_STATUS`),
  KEY `idx_ide_cl_session` (`CL_FILE_SESSION_ID`),
  KEY `idx_ide_ia_status` (`IA_ARCHIVE_STATUS`),
  KEY `idx_ide_ia_file` (`IA_ARCHIVE_FILE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: ITEM_DETAILS_REC (556 rows)
DROP TABLE IF EXISTS `ITEM_DETAILS_REC`;
CREATE TABLE `ITEM_DETAILS_REC` (
  `FILE_ID` bigint NOT NULL,
  `CASHLTR_ID` bigint NOT NULL,
  `BUNDLE_ID` bigint NOT NULL,
  `PAYMENT_ID` bigint NOT NULL,
  `RECORD_TYPE` smallint NOT NULL,
  `RECORD_DATA` mediumtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`FILE_ID`,`CASHLTR_ID`,`BUNDLE_ID`,`PAYMENT_ID`,`RECORD_TYPE`),
  KEY `PAYMENT_ID` (`PAYMENT_ID`),
  CONSTRAINT `ITEM_DETAILS_REC_ibfk_1` FOREIGN KEY (`PAYMENT_ID`) REFERENCES `ITEM_DETAILS` (`PAYMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: PRIORITY_BAND_MASTER (5 rows)
DROP TABLE IF EXISTS `PRIORITY_BAND_MASTER`;
CREATE TABLE `PRIORITY_BAND_MASTER` (
  `priority_band` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `severity_order` int NOT NULL,
  `severity_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `auto_return_flag` tinyint(1) DEFAULT '0',
  `ops_repairable_flag` tinyint(1) DEFAULT '0',
  `active_flag` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`priority_band`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: REVIEW_OUTCOME_MASTER (4 rows)
DROP TABLE IF EXISTS `REVIEW_OUTCOME_MASTER`;
CREATE TABLE `REVIEW_OUTCOME_MASTER` (
  `review_outcome_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `review_outcome_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mapped_x9_code` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `active_flag` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`review_outcome_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: USER_DETAILS (9 rows)
DROP TABLE IF EXISTS `USER_DETAILS`;
CREATE TABLE `USER_DETAILS` (
  `USER_ID` int NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(50) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `FIRST_NAME` varchar(50) NOT NULL,
  `LAST_NAME` varchar(50) NOT NULL,
  `ROLE` varchar(30) NOT NULL DEFAULT 'OPERATOR',
  `STATUS` varchar(10) NOT NULL DEFAULT 'ACTIVE',
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USERNAME` (`USERNAME`),
  UNIQUE KEY `EMAIL` (`EMAIL`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: USER_PRIVILEGES (32 rows)
DROP TABLE IF EXISTS `USER_PRIVILEGES`;
CREATE TABLE `USER_PRIVILEGES` (
  `PRIVILEGE_ID` int NOT NULL AUTO_INCREMENT,
  `USER_ID` int NOT NULL,
  `PRIVILEGE` varchar(50) NOT NULL,
  `GRANTED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PRIVILEGE_ID`),
  UNIQUE KEY `UK_USER_PRIVILEGE` (`USER_ID`,`PRIVILEGE`),
  CONSTRAINT `USER_PRIVILEGES_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER_DETAILS` (`USER_ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table: users (6 rows)
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` enum('ADMIN','OPERATOR','AUDITOR') COLLATE utf8mb4_unicode_ci NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `status` enum('ACTIVE','INACTIVE') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_6dotkott2kjsp8vw4d0m25fb7` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

