-- ============================================================================
-- POSTING_EOD_FILES — Registry of files generated by the Posting-EOD engine
-- ============================================================================
-- Tracks every file produced during EOD processing (posting extracts, GL
-- extracts, and reports). Sibling of CL_X9_FILE (CashLetter engine) and
-- IA_ARCHIVE_FILE (Image Archive engine), which are already provisioned here.
--
-- Previously this table was only created by the Posting engine's own migrations
-- (V1 base, V2 validation+S3, V3 transmit), so a freshly onboarded tenant
-- lacked it. Adding it here — with the v0.8 validation + S3-durability columns
-- AND the transmit column folded in — closes that gap.
--
-- Columns folded in from the Posting engine migrations:
--   V2: CHECKSUM, S3_UPLOADED_AT, VALIDATION_STATUS, VALIDATION_DETAILS
--   V3: TRANSMITTED_AT (file transmit — finding #14)
-- ============================================================================
USE ${DB_NAME_PRIMARY};

CREATE TABLE IF NOT EXISTS `POSTING_EOD_FILES` (
    `ID`                 BIGINT          NOT NULL AUTO_INCREMENT,
    `FILE_TYPE`          VARCHAR(30)     NOT NULL COMMENT 'POSTING | GL_EXTRACT | REPORT',
    `FILE_NAME`          VARCHAR(255)    NOT NULL COMMENT 'Generated filename e.g. POSTING_9_2026-07-20_170317.dat',
    `S3_KEY`             VARCHAR(512)    NULL     COMMENT 'Full S3 object key once uploaded',
    `S3_BUCKET`          VARCHAR(128)    NULL     COMMENT 'S3 bucket name',
    `S3_UPLOADED_AT`     TIMESTAMP       NULL     COMMENT 'When the file was uploaded to S3 (NULL until uploaded)',
    `TRANSMITTED_AT`     TIMESTAMP       NULL     COMMENT 'When the file was transmitted downstream (NULL until transmitted)',
    `FILE_SIZE_BYTES`    BIGINT          NULL     COMMENT 'File size in bytes',
    `CHECKSUM`           VARCHAR(64)     NULL     COMMENT 'SHA-256 hex checksum of the generated file',
    `BUSINESS_DATE`      VARCHAR(10)     NOT NULL COMMENT 'Business date the file belongs to (YYYY-MM-DD or YYYYMMDD)',
    `CASHLTR_ID`         BIGINT          NULL     COMMENT 'FK to CASH_LETTER_DETAILS.CASHLTR_ID (nullable for reports/GL spanning multiple CLs)',
    `FILE_ID`            BIGINT          NULL     COMMENT 'FK to INBOUND_FILE_DETAILS.FILE_ID (nullable)',
    `BIN_NUMBER`         INT             NULL     COMMENT 'BIN number this file was generated for (nullable for reports)',
    `COLLECTION_CODE`    VARCHAR(20)     NULL     COMMENT 'Collection code context',
    `STATUS`             VARCHAR(30)     NOT NULL DEFAULT 'GENERATED' COMMENT 'GENERATED | UPLOADED_S3 | TRANSMITTED | VALIDATION_FAILED | FAILED',
    `VALIDATION_STATUS`  VARCHAR(20)     NULL     COMMENT 'PASSED | FAILED | SKIPPED',
    `VALIDATION_DETAILS` TEXT            NULL     COMMENT 'Validation pass summary or failure reasons',
    `GENERATED_AT`       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When the file was generated',
    `GENERATED_BY`       VARCHAR(100)    NULL     COMMENT 'User or system that triggered generation',
    `ITEM_COUNT`         INT             NULL     COMMENT 'Number of items/records in the file',
    `TOTAL_AMOUNT`       DECIMAL(15,2)   NULL     COMMENT 'Total dollar amount covered by the file',
    `ERROR_DETAILS`      TEXT            NULL     COMMENT 'Error message if STATUS=FAILED',
    PRIMARY KEY (`ID`),
    INDEX `idx_pef_business_date` (`BUSINESS_DATE`),
    INDEX `idx_pef_file_type` (`FILE_TYPE`),
    INDEX `idx_pef_status` (`STATUS`),
    INDEX `idx_pef_validation_status` (`VALIDATION_STATUS`),
    INDEX `idx_pef_cashltr_id` (`CASHLTR_ID`),
    INDEX `idx_pef_bin_number` (`BIN_NUMBER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SELECT 'POSTING_EOD_FILES table provisioned (incl. TRANSMITTED_AT)' AS result;
