-- ============================================================================
-- ITEM_DETAILS_ADDENDA — Type 26 Check Detail Addendum A (BOFD)
-- One row per addendum; ADDENDA_SEQ=1 is Bank of First Deposit.
-- Run against: check_payment_platform (${DB_NAME_PRIMARY})
-- ============================================================================

USE ${DB_NAME_PRIMARY};

CREATE TABLE IF NOT EXISTS ITEM_DETAILS_ADDENDA (
  ADDENDA_ID BIGINT NOT NULL AUTO_INCREMENT,
  PAYMENT_ID BIGINT NOT NULL,
  PAYMENT_TRACKING_NUMBER VARCHAR(64) NULL,
  PROCESSING_BUSINESS_DATE DATE NULL,
  ADDENDA_SEQ INT NOT NULL DEFAULT 1,
  BOFD_ROUTING_NUMBER CHAR(9) NULL,
  BOFD_BUSINESS_DATE DATE NULL,
  BOFD_ITEM_SEQUENCE_NUMBER VARCHAR(15) NULL,
  BOFD_DEPOSIT_ACCOUNT VARCHAR(18) NULL,
  BOFD_DEPOSIT_BRANCH VARCHAR(5) NULL,
  RECORD_JSON MEDIUMTEXT NULL,
  PRIMARY KEY (ADDENDA_ID),
  KEY idx_ida_payment (PAYMENT_ID),
  CONSTRAINT ITEM_DETAILS_ADDENDA_ibfk_1
    FOREIGN KEY (PAYMENT_ID) REFERENCES ITEM_DETAILS (PAYMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SELECT 'ITEM_DETAILS_ADDENDA ready' AS result;
