-- ============================================================================
-- POSTING_EOD_FILES — Registry of files generated by the Posting-EOD Engine
-- Source shape: ecs-posting-eod-extract-engine V1__create_posting_eod_files.sql
-- Run against: check_payment_platform (${DB_NAME_PRIMARY})
-- ============================================================================

USE ${DB_NAME_PRIMARY};

CREATE TABLE IF NOT EXISTS POSTING_EOD_FILES (
    ID                  BIGINT          NOT NULL AUTO_INCREMENT,
    FILE_TYPE           VARCHAR(30)     NOT NULL COMMENT 'POSTING | GL_EXTRACT | REPORT',
    FILE_NAME           VARCHAR(255)    NOT NULL COMMENT 'Generated filename e.g. POSTING_9_2026-07-20_170317.dat',
    S3_KEY              VARCHAR(512)    NULL     COMMENT 'Full S3 object key once uploaded',
    S3_BUCKET           VARCHAR(128)    NULL     COMMENT 'S3 bucket name',
    FILE_SIZE_BYTES     BIGINT          NULL     COMMENT 'File size in bytes',
    BUSINESS_DATE       VARCHAR(10)     NOT NULL COMMENT 'Business date the file belongs to (YYYY-MM-DD or YYYYMMDD)',
    CASHLTR_ID          BIGINT          NULL     COMMENT 'FK to CASH_LETTER_DETAILS.CASHLTR_ID (nullable for reports spanning multiple CLs)',
    FILE_ID             BIGINT          NULL     COMMENT 'FK to INBOUND_FILE_DETAILS.FILE_ID (nullable)',
    BIN_NUMBER          INT             NULL     COMMENT 'BIN number this file was generated for (nullable for reports)',
    COLLECTION_CODE     VARCHAR(20)     NULL     COMMENT 'Collection code context',
    STATUS              VARCHAR(30)     NOT NULL DEFAULT 'GENERATED' COMMENT 'GENERATED | UPLOADED_S3 | TRANSMITTED | FAILED',
    GENERATED_AT        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When the file was generated',
    GENERATED_BY        VARCHAR(100)    NULL     COMMENT 'User or system that triggered generation',
    ITEM_COUNT          INT             NULL     COMMENT 'Number of items/records in the file',
    TOTAL_AMOUNT        DECIMAL(15,2)   NULL     COMMENT 'Total dollar amount covered by the file',
    ERROR_DETAILS       TEXT            NULL     COMMENT 'Error message if STATUS=FAILED',
    PRIMARY KEY (ID),
    INDEX idx_pef_business_date (BUSINESS_DATE),
    INDEX idx_pef_file_type (FILE_TYPE),
    INDEX idx_pef_status (STATUS),
    INDEX idx_pef_cashltr_id (CASHLTR_ID),
    INDEX idx_pef_bin_number (BIN_NUMBER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SELECT 'POSTING_EOD_FILES ready' AS result;
